name: image_network
description: Image Network is a package that allows you to render images on the web using CanvasKit without having problems with CORS
version: 2.5.4
homepage: https://github.com/gabrielpatricksouza/image_network
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  # webviewimage: ^0.0.6
  webviewimage:
    path: ../../Others/webviewimage
  # webviewimage:
  #   git:
  #     url: https://github.com/oliverbytes/webviewimage.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
