name: image_network
description: Image Network is a package that allows you to render images on the web using CanvasKit without having problems with CORS
version: 2.5.4
homepage: https://github.com/gabrielpatricksouza/image_network

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  # webviewimage: ^0.0.6
  webviewimage:
    git:
      url: https://github.com/oliverbytes/webviewimage.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  uuid: ^3.0.7

flutter:
